### ISSUE TITLE
Meta: Improve test coverage for CI

### ISSUE THREAD

**Issue by simonleung8** [kubernetes-sigs/service-catalog#521]
Need to have adequate test coverage for our CI

Packages that need unit testing:

- [ ] `cmd/apiserver`
- [ ]  `cmd/controller-manager`
- [ ]  `pkg/apis`
- [ ]  `pkg/apiserver`
- [ ]  `pkg/brokerapi`
- [ ]  `pkg/controller`
- [ ]  `pkg/openapi`
- [ ]  `pkg/registry/servicecatalog/binding`
- [ ]  `pkg/registry/servicecatalog/broker`
- [ ]  `pkg/registry/servicecatalog/instance`
- [ ]  `pkg/registry/servicecatalog/rest`
- [ ]  `pkg/registry/servicecatalog/server`
- [ ]  `pkg/registry/servicecatalog/serviceclass`
- [ ]  `pkg/storage` (#700)
- [ ]  `pkg/util`

**Comment by arschles** [comment]
I've added this to `0.0.2`, as testing is a large task for that milestone. This issue can and should be split apart, and may move into new milestones.

**Comment by pmorie** [comment]
Moving to 0.0.3 because this is not complete.

**Comment by arschles** [comment]
Moving this out of a milestone because it's a meta issue
